export  { default as Dashboard} from './Dashboard/Dashboard'
export  { default as Profile} from './Profile/Profile'
export  { default as Markets} from './Markets/Markets'
export  { default as Coins} from './Coins/Coins'
export  { default as News} from './News/News'
